<?php
bolt_decrypt( __FILE__ , 'I4VcQv'); return 0;
##!!!##CgcKB2teamJwbV5gYh0+bW1ZSmxhYmlwOAoHCgdycGIdRmlpcmpma15xYllBXnFeX15wYllCaWxucmJrcVlDXmBxbG9mYnBZRV5wQ15gcWxvdjgKB3JwYh1GaWlyamZrXnFiWUFecV5fXnBiWUJpbG5yYmtxWUpsYWJpOAoHCgdgaV5wcB1KZmBvbHBsY3FAbGtjZmRyb15xZmxrHWJ1cWJrYXAdSmxhYmkKB3gKBx0dHR1ycGIdRV5wQ15gcWxvdjgKBwoHCgcdHR0dbXJfaWZgHSFkcl5vYWJhHTodWFo4Cgd6Cgc=