<?php
bolt_decrypt( __FILE__ , '6wJDAy'); return 0;
##!!!##Av8C/2NWYlpoZVZYWhU2ZWVRQmRZWmFoMAL/Av9qaFoVPmFhamJeY1ZpWlE5VmlWV1ZoWlE6YWRmalpjaVE7VlhpZGdeWmhRPVZoO1ZYaWRnbjAC/2poWhU+YWFqYl5jVmlaUTlWaVZXVmhaUTphZGZqWmNpUUJkWVphMAL/Av9YYVZoaBVFZ15rVlhuFVptaVpjWWgVQmRZWmEC/3AC/xUVFRVqaFoVPVZoO1ZYaWRnbjAC/3IC/w==