<?php
bolt_decrypt( __FILE__ , 'A8wk0n'); return 0;
##!!!##BgMGA2daZl5saVpcXhk6aWlVRmhdXmVsNAYDBgNubF4ZQmVlbmZiZ1ptXlU9Wm1aW1psXlU+ZWhqbl5nbVU/WlxtaGtiXmxVQVpsP1pcbWhrcjQGA25sXhlCZWVuZmJnWm1eVT1abVpbWmxeVT5laGpuXmdtVUZoXV5lNAYDBgNcZVpsbBlCZ1xiXV5nbUtibGQZXnFtXmddbBlGaF1eZQYDdAYDGRkZGW5sXhlBWmw/WlxtaGtyNAYDdgYD