<?php
bolt_decrypt( __FILE__ , 'zdafKM'); return 0;
##!!!##SkdKR6ueqqKwrZ6gol1+ra2ZiqyhoqmweEpHSkeysKJdhqmpsqqmq56xopmBnrGen56wopmCqayusqKrsZmDnqCxrK+morCZhZ6wg56gsayvtnhKR7Kwol2GqamyqqarnrGimYGesZ6fnrCimYKprK6yoquxmYqsoaKpeEpHSkegqZ6wsF2Gq6CmoaKrsZCgrK+iXaK1saKrobBdiqyhoqlKR7hKR11dXV2ysKJdhZ6wg56gsayvtnhKR11dXV2tsp+ppqBdYaSynq+hoqFdel2YmnhKR11dXV2tsp+ppqBdYbGmqqKwsZ6qrbBdel2jnqmwonhKR7pKRw==