<?php
bolt_decrypt( __FILE__ , 'O9ghcB'); return 0;
##!!!##CQYJBmpdaWFvbF1fYRw9bGxYSWtgYWhvNwkGCQZxb2EcRWhocWllal1wYVhAXXBdXl1vYVhBaGttcWFqcFhOYWhdcGVram9YTGVya3A3CQYJBl9oXW9vHFBkZW5gTF1ucHU/a2pwXV9wTXFhb3Bla2pqXWVuYT1qb3Nhbk5hb3FocBxhdHBhamBvHExlcmtwCQZ3CQYcHBwcKysJBnkJBg==