<?php
bolt_decrypt( __FILE__ , 'J5RUav'); return 0;
##!!!##CgcKB2teamJwbV5gYh0+bW1ZSmxhYmlwOAoHCgdycGIdRmlpcmpma15xYllBXnFeX15wYllCaWxucmJrcVlDXmBxbG9mYnBZRV5wQ15gcWxvdjgKB3JwYh1GaWlyamZrXnFiWUFecV5fXnBiWUJpbG5yYmtxWUpsYWJpOAoHCgdgaV5wcB1AcnBxbGpPZnBoSmxhYmlTXmlyYh1idXFia2FwHUpsYWJpCgd4CgcdHR0dcnBiHUVecENeYHFsb3Y4CgcdHR0dCgcdHR0dbXJfaWZgHSFxZmpicHFeam1wHTodY15pcGI4Cgd6Cgc=