<?php
bolt_decrypt( __FILE__ , 'fOZZgq'); return 0;
##!!!##TktOS6+irqa0saKkpmGCsbGdlKazt6qkprSdlK60fE5LTku2tKZhgrGxnYqvtaazp6KkprSdlK60iq+1prOnoqSmfE5LTkukraK0tGGUrrSUprO3qqSmkbOwt6qlprNOS7xOS2FhYWGxtqOtqqRhp7avpLWqsK9htKavpWmUrrSKr7Wms6eipKZhZbSutI6mtamwpW1hZba0prOKpW1hZa6mtLSiqKZqTkthYWFhvE5LYWFhYWFhYWGzprW2s69hZbSutI6mtamwpW5/tKavpZSutGlltrSms4qlbWFlrqa0tKKopmp8TkthYWFhvk5Lvk5L